services:
  ce-web-app:
    build:
      context: .
    ports:
        - "8000:8000"
    volumes:
      - ./service_app:/service
    environment:
      - DB_HOST=ce-database
      - DB_NAME=postgres
      - DB_USER=postgres
      - DB_PASS=postgres
    command: >
      sh -c "python manage.py runserver 0.0.0.0:8000"
    depends_on:
      - ce-database

  ce-database:
    image: postgres:14.6-alpine
    ports:
        - "54321:5432"
    volumes:
      - C:\DockerVolumes\DjangoProject\pgdata:/var/lib/postgresql/data
    environment:
      - POSTGRES_DB=postgres
      - POSTGRES_USER=postgres
      - POSTGRES_PASSWORD=postgres

  redis:
    image: redis:7.0.5-alpine
    hostname: redis

  worker:
    build:
      context: .
    hostname: worker
    entrypoint: celery
    command: -A celery_app.app worker --loglevel=info
    volumes:
      - ./service_app:/service
    links:
      - redis
    depends_on:
      - redis
      - ce-database
    environment:
      - DB_HOST=ce-database
      - DB_NAME=postgres
      - DB_USER=postgres
      - DB_PASS=postgres

  worker2:
    build:
      context: .
    hostname: worker2
    entrypoint: celery
    command: -A celery_app.app worker --loglevel=info
    volumes:
      - ./service_app:/service
    links:
      - redis
    depends_on:
      - redis
      - ce-database
    environment:
      - DB_HOST=ce-database
      - DB_NAME=postgres
      - DB_USER=postgres
      - DB_PASS=postgres


  flower:
    build:
      context: .
    hostname: flower
    entrypoint: celery
    command: -A celery_app.app flower
    volumes:
      - ./service_app:/service
    ports:
        - "5555:5555"
    links:
      - redis
    depends_on:
      - redis
